package service

import (
	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/model"
	"gorm.io/gorm"
)

// SeedStudioCatalog populates all MVP tools and templates into PostgreSQL.
func SeedStudioCatalog(db *gorm.DB) error {
	if db == nil {
		return nil
	}

	now := common.GetTimestamp()

	// 1. MVP Tools (Section 5 & 7)
	tools := []model.StudioToolDefinition{
		// Active Image MVP Tools
		{
			Id:               "image-generate",
			Slug:             "image-generator",
			Name:             "Image Generate",
			DisplayName:      "สร้างภาพ AI อัจฉริยะ (Flux.1)",
			Description:      "สร้างภาพความละเอียดสูงจากข้อความด้วยโมเดล Flux.1 ให้รายละเอียดคมชัด สมจริง รองรับสไตล์ภาพหลากหลาย",
			Category:         "image",
			InputSchema:      `{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string","description":"Prompt คำบรรยายภาพที่ต้องการสร้าง"},"aspect_ratio":{"type":"string","enum":["1:1","4:5","9:16","16:9"],"default":"1:1"},"negative_prompt":{"type":"string"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    20971520, // 20MB
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       5,
			QuotaCost:        5000,
			RiskClass:        "low",
			DisplayOrder:     1,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/flux/schnell",
			MarginPercent:    60.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "image-upscale",
			Slug:             "image-upscale",
			Name:             "Image Upscale (4K)",
			DisplayName:      "ขยายภาพคมชัด 4K (Clarity Upscaler)",
			Description:      "เพิ่มความละเอียดของภาพขึ้น 4 เท่า โดยไม่แตก พร้อมฟื้นฟูรายละเอียดพื้นผิวและ Texture อย่างเป็นธรรมชาติ",
			Category:         "utility",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string","description":"URL หรือรูปภาพที่ต้องการขยาย"},"scale":{"type":"integer","enum":[2,4],"default":4}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280, // 30MB
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       25,
			QuotaCost:        25000,
			RiskClass:        "low",
			DisplayOrder:     2,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/clarity-upscaler",
			MarginPercent:    70.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "background-remove",
			Slug:             "background-remove",
			Name:             "Background Remove",
			DisplayName:      "ลบพื้นหลังอัจฉริยะ (BiRefNet)",
			Description:      "ตัดพื้นหลังออกอย่างแม่นยำด้วย BiRefNet แยกเส้นผมและขอบวัตถุได้อย่างสมบูรณ์แบบ ได้ภาพโปร่งใส PNG ทันที",
			Category:         "utility",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string","description":"รูปภาพที่ต้องการลบพื้นหลัง"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       10,
			QuotaCost:        10000,
			RiskClass:        "low",
			DisplayOrder:     3,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/birefnet",
			MarginPercent:    75.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "product-photo",
			Slug:             "product-photo",
			Name:             "Product Photo Studio",
			DisplayName:      "สตูดิโอถ่ายภาพสินค้าโฆษณา",
			Description:      "จัดวางภาพสินค้าของคุณลงบนฉากจัดแสงระดับสตูดิโอมืออาชีพอัตโนมัติ เพิ่มยอดขายบน Shopee, Lazada และ TikTok Shop",
			Category:         "product",
			InputSchema:      `{"type":"object","required":["image_url","prompt"],"properties":{"image_url":{"type":"string","description":"ภาพสินค้าพื้นหลังเรียบ"},"prompt":{"type":"string","description":"ลักษณะฉากหลังและบรรยากาศ"},"aspect_ratio":{"type":"string","enum":["1:1","4:5","9:16"],"default":"1:1"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       50,
			QuotaCost:        50000,
			RiskClass:        "low",
			DisplayOrder:     4,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/product-photography",
			MarginPercent:    65.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "image-extend",
			Slug:             "image-extend",
			Name:             "Image Extend (Outpaint)",
			DisplayName:      "ขยายขอบเขตภาพ (Outpaint Fill)",
			Description:      "ขยายภาพออกด้านข้างหรือบนล่างอย่างไร้รอยต่อ เติมเต็มฉากหลังให้เข้ากับสัดส่วน Story 9:16 หรือ แบนเนอร์ 16:9",
			Category:         "image",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string"},"target_aspect_ratio":{"type":"string","enum":["16:9","9:16","4:5"],"default":"16:9"},"prompt":{"type":"string"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       30,
			QuotaCost:        30000,
			RiskClass:        "low",
			DisplayOrder:     5,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/flux-fill",
			MarginPercent:    65.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "object-erase",
			Slug:             "object-erase",
			Name:             "Object Erase / Inpaint",
			DisplayName:      "ลบวัตถุและตกแต่งภาพ (Inpaint)",
			Description:      "ลบวัตถุที่ไม่ต้องการ ลายน้ำ หรือบุคคลส่วนเกินออกจากภาพ พร้อมเติมเต็มพื้นผิวให้กลมกลืนอย่างสมบูรณ์",
			Category:         "utility",
			InputSchema:      `{"type":"object","required":["image_url","mask_url"],"properties":{"image_url":{"type":"string"},"mask_url":{"type":"string"},"prompt":{"type":"string"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       30,
			QuotaCost:        30000,
			RiskClass:        "low",
			DisplayOrder:     6,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/flux/dev/inpainting",
			MarginPercent:    66.7,
			Status:           model.StudioToolStateActive,
		},

		// Active Video MVP Tool
		{
			Id:               "image-to-video",
			Slug:             "image-to-video",
			Name:             "Image to Video",
			DisplayName:      "แปลงภาพนิ่งเป็นวิดีโอ (Wan 2.2 / Kling)",
			Description:      "ขยับภาพถ่ายสินค้า ภาพวิว หรือตัวละครให้มีชีวิตชีวาด้วยการเคลื่อนไหวที่เป็นธรรมชาติ สร้างวิดีโอ 5 วินาทีความละเอียดสูง",
			Category:         "video",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string"},"motion_prompt":{"type":"string"},"duration":{"type":"integer","enum":[5],"default":5}}}`,
			OutputType:       "video/mp4",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       125,
			QuotaCost:        125000,
			RiskClass:        "low",
			DisplayOrder:     7,
			PrimaryProvider:  "fal",
			PrimaryModel:     "wan-video/wan-2.2",
			MarginPercent:    68.0,
			Status:           model.StudioToolStateActive,
		},

		// Disabled / Coming Soon Tools (Section 5)
		{
			Id:               "text-to-video",
			Slug:             "text-to-video",
			Name:             "Text to Video",
			DisplayName:      "สร้างวิดีโอจากข้อความ (เร็วๆ นี้)",
			Description:      "สร้างคลิปวิดีโอระดับภาพยนตร์จากคำบรรยายข้อความ",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       125,
			QuotaCost:        125000,
			DisplayOrder:     8,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "lip-sync",
			Slug:             "lip-sync",
			Name:             "Lip Sync Video",
			DisplayName:      "ลิปซิงก์เสียงและขยับปาก (เร็วๆ นี้)",
			Description:      "ซิงก์เสียงพูดภาษาไทยและภาษาอังกฤษเข้ากับริมฝีปากของวิดีโอ",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       75,
			QuotaCost:        75000,
			DisplayOrder:     9,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "face-swap",
			Slug:             "face-swap",
			Name:             "Face Swap Studio",
			DisplayName:      "สลับใบหน้าระดับโปร (เร็วๆ นี้)",
			Description:      "เปลี่ยนหน้าบุคคลในภาพด้วยความละเอียดระดับสตูดิโอ (ต้องการการยืนยันสิทธิ์)",
			Category:         "image",
			OutputType:       "image/png",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       40,
			QuotaCost:        40000,
			DisplayOrder:     10,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "talking-avatar",
			Slug:             "talking-avatar",
			Name:             "Talking Avatar",
			DisplayName:      "อวตารผู้ประกาศข่าว (เร็วๆ นี้)",
			Description:      "สร้างผู้ประกาศข่าวเสมือนจริงพูดรายงานจากสคริปต์",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       100,
			QuotaCost:        100000,
			DisplayOrder:     11,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "video-upscale",
			Slug:             "video-upscale",
			Name:             "Video Upscale (HD)",
			DisplayName:      "เพิ่มความคมชัดวิดีโอ (เร็วๆ นี้)",
			Description:      "ขยายวิดีโอความละเอียดต่ำขึ้นเป็น Full HD และ 4K",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       100,
			QuotaCost:        100000,
			DisplayOrder:     12,
			Status:           model.StudioToolStateComingSoon,
		},
	}

	for _, t := range tools {
		t.CreatedAt = now
		t.UpdatedAt = now
		_ = db.Where("id = ?", t.Id).Assign(t).FirstOrCreate(&t)
	}

	// 2. Useful Presets & Templates (Section 8)
	templates := []model.StudioToolTemplate{
		// Product Photo Templates
		{
			Id:                "tpl-prod-white-studio",
			ToolId:            "product-photo",
			Slug:              "white-studio",
			Name:              "White Studio",
			DisplayName:       "สตูดิโอขาวไร้รอยต่อ (White Seamless)",
			Description:       "ฉากหลังสีขาวสะอาดตาพร้อมเงาสะท้อนระดับสตูดิโอ เหมาะสำหรับภาพสินค้าบน E-commerce",
			Category:          "product",
			PresetPrompt:      "Clean seamless white studio background, commercial advertising lighting, soft ambient reflection, high-end product showcase, 8k resolution",
			PresetAspectRatio: "1:1",
			DisplayOrder:      1,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-luxury-black",
			ToolId:            "product-photo",
			Slug:              "luxury-black",
			Name:              "Luxury Black",
			DisplayName:       "หรูหราพรีเมียมสีดำ (Luxury Dark Elegance)",
			Description:       "ฉากหลังสีดำดาร์กโทน แสงไฟ Rim Light ขับเน้นรูปทรง สำหรับสินค้าไฮเอนด์และน้ำหอม",
			Category:          "product",
			PresetPrompt:      "Dark luxury minimalist stone background, dramatic moody rim light, premium cosmetic advertising, high contrast, elegant aesthetic",
			PresetAspectRatio: "1:1",
			DisplayOrder:      2,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-minimal-beige",
			ToolId:            "product-photo",
			Slug:              "minimal-beige",
			Name:              "Minimal Beige",
			DisplayName:       "มินิมอลเบจเอิร์ธโทน (Minimalist Warm Beige)",
			Description:       "โทนสีเบจและเนื้อไม้ธรรมชาติ สไตล์อบอุ่นสไตล์เกาหลี/มูจิ",
			Category:          "product",
			PresetPrompt:      "Warm beige linen background, wooden pedestal, soft natural morning sunlight casting organic leaf shadows, aesthetic lifestyle product shot",
			PresetAspectRatio: "4:5",
			DisplayOrder:      3,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-kitchen",
			ToolId:            "product-photo",
			Slug:              "kitchen-counter",
			Name:              "Modern Kitchen",
			DisplayName:       "เคาน์เตอร์ครัวโมเดิร์น (Modern Kitchen Counter)",
			Description:       "ฉากครัวหินอ่อนโมเดิร์น สำหรับสินค้าประเภทอาหาร เครื่องดื่ม และของใช้ในบ้าน",
			Category:          "product",
			PresetPrompt:      "Modern bright marble kitchen countertop, blurry warm kitchen background, daylight, lifestyle culinary photography",
			PresetAspectRatio: "1:1",
			DisplayOrder:      4,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-outdoor",
			ToolId:            "product-photo",
			Slug:              "outdoor-nature",
			Name:              "Outdoor Nature",
			DisplayName:       "ธรรมชาติกลางแจ้ง (Natural Outdoor Sun)",
			Description:       "ฉากธรรมชาติ ทุ่งหญ้า โขดหิน และแสงอาทิตย์ สำหรับสินค้าออร์แกนิกและสกินแคร์",
			Category:          "product",
			PresetPrompt:      "Natural outdoor setting on a smooth wet pebble stone, lush green foliage background bokeh, golden hour sunlight, organic aesthetic",
			PresetAspectRatio: "4:5",
			DisplayOrder:      5,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-shopee-square",
			ToolId:            "product-photo",
			Slug:              "shopee-square",
			Name:              "Shopee Square",
			DisplayName:       "จัตุรัส Shopee / Lazada (1:1)",
			Description:       "สัดส่วน 1:1 พร้อมพื้นที่กึ่งกลางเด่นชัด พร้อมสำหรับการใส่กรอบโปรโมชั่น",
			Category:          "product",
			PresetPrompt:      "Bright vibrant clean commercial background, studio illumination, centered focal composition, ready for marketplace listing",
			PresetAspectRatio: "1:1",
			DisplayOrder:      6,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-ig-portrait",
			ToolId:            "product-photo",
			Slug:              "instagram-4-5",
			Name:              "Instagram Feed (4:5)",
			DisplayName:       "โพสต์ Instagram (4:5)",
			Description:       "สัดส่วน 4:5 แนวตั้งที่กินพื้นที่หน้าจอมือถือมากที่สุด เพิ่ม Engagement ให้โพสต์",
			Category:          "product",
			PresetPrompt:      "Trendy aesthetic lifestyle magazine layout, 4:5 vertical framing, perfect lighting for social media feed",
			PresetAspectRatio: "4:5",
			DisplayOrder:      7,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-story-9-16",
			ToolId:            "product-photo",
			Slug:              "story-9-16",
			Name:              "Reels & TikTok Story (9:16)",
			DisplayName:       "สตอรี่เต็มจอ (9:16)",
			Description:       "สัดส่วน 9:16 เต็มจอมือถือ สำหรับ Story, TikTok และ YouTube Shorts",
			Category:          "product",
			PresetPrompt:      "Vertical 9:16 smartphone screen layout, commercial product placement with room for top and bottom text overlays",
			PresetAspectRatio: "9:16",
			DisplayOrder:      8,
			IsActive:          true,
		},

		// Image Generation Templates
		{
			Id:                "tpl-img-pro-portrait",
			ToolId:            "image-generate",
			Slug:              "professional-portrait",
			Name:              "Professional Portrait",
			DisplayName:       "ภาพถ่ายบุคคลระดับโปร (Pro Headshot)",
			Description:       "ภาพถ่ายโปรไฟล์มืออาชีพสำหรับ LinkedIn และ Resume แสงแฟลชสตูดิโอคมชัด",
			Category:          "portrait",
			PresetPrompt:      "Corporate executive portrait, sharp focus on eyes, 85mm f/1.4 lens photography, studio softbox illumination, high detail facial skin texture",
			PresetAspectRatio: "4:5",
			DisplayOrder:      10,
			IsActive:          true,
		},
		{
			Id:                "tpl-img-cinematic",
			ToolId:            "image-generate",
			Slug:              "cinematic-film",
			Name:              "Cinematic Film",
			DisplayName:       "ภาพยนตร์ฟิล์ม (Cinematic 35mm)",
			Description:       "โทนภาพยนตร์ฟิล์ม 35mm แสงไฟ Dramatic อารมณ์ภาพทรงพลัง",
			Category:          "creative",
			PresetPrompt:      "Cinematic 35mm film still, anamorphic lens flare, moody color grading, volumetric smoke and haze, cinematic lighting, masterpiece",
			PresetAspectRatio: "16:9",
			DisplayOrder:      11,
			IsActive:          true,
		},
		{
			Id:                "tpl-img-anime",
			ToolId:            "image-generate",
			Slug:              "modern-anime",
			Name:              "Modern Anime",
			DisplayName:       "อนิเมะญี่ปุ่นร่วมสมัย (Makoto Shinkai Style)",
			Description:       "สไตล์อนิเมะญี่ปุ่นสีสันสดใส ท้องฟ้าและแสงแดดสไตล์ภาพยนตร์แอนิเมชัน",
			Category:          "creative",
			PresetPrompt:      "Vibrant modern anime visual key, Makoto Shinkai aesthetic, detailed cloud formations, emotional lighting, expressive character lineart",
			PresetAspectRatio: "16:9",
			DisplayOrder:      12,
			IsActive:          true,
		},

		// Image to Video Templates
		{
			Id:                "tpl-vid-product-ad-5s",
			ToolId:            "image-to-video",
			Slug:              "product-ad-5s",
			Name:              "Product Ad 5s",
			DisplayName:       "โฆษณาสินค้า 5 วินาที (Commercial Motion)",
			Description:       "การเคลื่อนกล้องแบบ Smooth Glide เน้นความเงางามของสินค้า สำหรับยิงแอด",
			Category:          "motion",
			PresetPrompt:      "Smooth camera pan around product, gentle light reflections, slow motion commercial videography",
			PresetAspectRatio: "1:1",
			DisplayOrder:      20,
			IsActive:          true,
		},
		{
			Id:                "tpl-vid-orbit-motion",
			ToolId:            "image-to-video",
			Slug:              "orbit-motion",
			Name:              "Orbit Motion",
			DisplayName:       "กล้องหมุนรอบวัตถุ (Orbit 360)",
			Description:       "กล้องหมุนโค้ง 45 องศา สร้างมิติและความพรีเมียมให้วัตถุ",
			Category:          "motion",
			PresetPrompt:      "Slow rotational orbit camera motion, steady gimbal movement, 3D depth parallax",
			PresetAspectRatio: "16:9",
			DisplayOrder:      21,
			IsActive:          true,
		},
		{
			Id:                "tpl-vid-zoom-in",
			ToolId:            "image-to-video",
			Slug:              "cinematic-zoom-in",
			Name:              "Cinematic Zoom In",
			DisplayName:       "ดอลลี่ซูมเข้า (Cinematic Push In)",
			Description:       "กล้องค่อยๆ เคลื่อนที่เข้าหาจุดกึ่งกลางอย่างนุ่มนวล ดึงดูดสายตา",
			Category:          "motion",
			PresetPrompt:      "Smooth slow dolly push-in towards focal subject, cinematic motion blur, 24fps film feel",
			PresetAspectRatio: "4:5",
			DisplayOrder:      22,
			IsActive:          true,
		},
		{
			Id:                "tpl-vid-vertical-reel",
			ToolId:            "image-to-video",
			Slug:              "vertical-reel-9-16",
			Name:              "Vertical Reel Motion (9:16)",
			DisplayName:       "คลิปสั้นแนวตั้ง TikTok/Reels (9:16)",
			Description:       "การเคลื่อนไหวน่าติดตาม สัดส่วน 9:16 สำหรับคลิปสั้นบนโซเชียลมีเดีย",
			Category:          "motion",
			PresetPrompt:      "Dynamic vertical video motion for TikTok and Instagram Reels, smooth transitions and lifelike movement",
			PresetAspectRatio: "9:16",
			DisplayOrder:      23,
			IsActive:          true,
		},
	}

	for _, tpl := range templates {
		tpl.CreatedAt = now
		tpl.UpdatedAt = now
		_ = db.Where("id = ?", tpl.Id).Assign(tpl).FirstOrCreate(&tpl)
	}

	return nil
}
