package service

import (
	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/model"
	"gorm.io/gorm"
)

// SeedStudioCatalog populates all MVP tools and templates into PostgreSQL.
func SeedStudioCatalog(db *gorm.DB) error {
	if db == nil {
		return nil
	}

	now := common.GetTimestamp()

	// 1. MVP Tools (Section 5 & 7)
	tools := []model.StudioToolDefinition{
		// Active Image MVP Tools
		{
			Id:               "image-generate",
			Slug:             "image-generator",
			Name:             "Image Generate",
			DisplayName:      "สร้างภาพ AI อัจฉริยะ (Flux.1)",
			Description:      "สร้างภาพความละเอียดสูงจากข้อความด้วยโมเดล Flux.1 ให้รายละเอียดคมชัด สมจริง รองรับสไตล์ภาพหลากหลาย",
			Category:         "image",
			InputSchema:      `{"type":"object","required":["prompt"],"properties":{"prompt":{"type":"string","description":"Prompt คำบรรยายภาพที่ต้องการสร้าง"},"aspect_ratio":{"type":"string","enum":["1:1","4:5","9:16","16:9"],"default":"1:1"},"negative_prompt":{"type":"string"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    20971520, // 20MB
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       5,
			QuotaCost:        5000,
			RiskClass:        "low",
			DisplayOrder:     1,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/flux/schnell",
			MarginPercent:    60.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "image-upscale",
			Slug:             "image-upscale",
			Name:             "Image Upscale (4K)",
			DisplayName:      "ขยายภาพคมชัด 4K (Clarity Upscaler)",
			Description:      "เพิ่มความละเอียดของภาพขึ้น 4 เท่า โดยไม่แตก พร้อมฟื้นฟูรายละเอียดพื้นผิวและ Texture อย่างเป็นธรรมชาติ",
			Category:         "utility",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string","description":"URL หรือรูปภาพที่ต้องการขยาย"},"scale":{"type":"integer","enum":[2,4],"default":4}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280, // 30MB
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       25,
			QuotaCost:        25000,
			RiskClass:        "low",
			DisplayOrder:     2,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/clarity-upscaler",
			MarginPercent:    70.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "background-remove",
			Slug:             "background-remove",
			Name:             "Background Remove",
			DisplayName:      "ลบพื้นหลังอัจฉริยะ (BiRefNet)",
			Description:      "ตัดพื้นหลังออกอย่างแม่นยำด้วย BiRefNet แยกเส้นผมและขอบวัตถุได้อย่างสมบูรณ์แบบ ได้ภาพโปร่งใส PNG ทันที",
			Category:         "utility",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string","description":"รูปภาพที่ต้องการลบพื้นหลัง"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       10,
			QuotaCost:        10000,
			RiskClass:        "low",
			DisplayOrder:     3,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/birefnet",
			MarginPercent:    75.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "product-photo",
			Slug:             "product-photo",
			Name:             "Product Photo Studio",
			DisplayName:      "สตูดิโอถ่ายภาพสินค้าโฆษณา (E-Commerce)",
			Description:      "จัดวางภาพสินค้าของคุณลงบนฉากจัดแสงระดับสตูดิโอมืออาชีพอัตโนมัติ เพิ่มยอดขายบน Shopee, Lazada และ TikTok Shop",
			Category:         "product",
			InputSchema:      `{"type":"object","required":["image_url","prompt"],"properties":{"image_url":{"type":"string","description":"ภาพสินค้าต้นฉบับ"},"prompt":{"type":"string","description":"ลักษณะฉากหลังและบรรยากาศ"},"aspect_ratio":{"type":"string","enum":["1:1","4:5","9:16"],"default":"1:1"},"marketplace":{"type":"string","enum":["shopee","lazada","instagram","story","tiktok"],"default":"shopee"},"pack_size":{"type":"integer","enum":[1,4],"default":1},"auto_remove_bg":{"type":"boolean","default":true},"reference_image_url":{"type":"string","description":"ภาพอ้างอิงสไตล์ฉากหลัง"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       50,
			QuotaCost:        50000,
			RiskClass:        "low",
			DisplayOrder:     4,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/product-photography",
			MarginPercent:    65.0,
			Status:           model.StudioToolStateActive,
		},
		{
			Id:               "image-extend",
			Slug:             "image-extend",
			Name:             "Image Extend (Outpaint)",
			DisplayName:      "ขยายขอบเขตภาพ (Outpaint Fill)",
			Description:      "ขยายภาพออกด้านข้างหรือบนล่างอย่างไร้รอยต่อ เติมเต็มฉากหลังให้เข้ากับสัดส่วน Story 9:16 หรือ แบนเนอร์ 16:9",
			Category:         "image",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string"},"target_aspect_ratio":{"type":"string","enum":["16:9","9:16","4:5"],"default":"16:9"},"prompt":{"type":"string"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       30,
			QuotaCost:        30000,
			RiskClass:        "low",
			DisplayOrder:     5,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/flux-fill",
			MarginPercent:    65.0,
			Status:           model.StudioToolStateBeta,
		},
		{
			Id:               "object-erase",
			Slug:             "object-erase",
			Name:             "Object Erase / Inpaint",
			DisplayName:      "ลบวัตถุและทำความสะอาดภาพ (Object Cleanup)",
			Description:      "ลบวัตถุที่ไม่ต้องการ ส่วนเกิน หรือริ้วรอยออกจากภาพ (Object Cleanup & Inpainting) พร้อมเติมเต็มพื้นผิวให้กลมกลืนอย่างสมบูรณ์",
			Category:         "utility",
			InputSchema:      `{"type":"object","required":["image_url","mask_url"],"properties":{"image_url":{"type":"string"},"mask_url":{"type":"string"},"prompt":{"type":"string"}}}`,
			OutputType:       "image/png",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       30,
			QuotaCost:        30000,
			RiskClass:        "low",
			DisplayOrder:     6,
			PrimaryProvider:  "fal",
			PrimaryModel:     "fal-ai/flux/dev/inpainting",
			MarginPercent:    66.7,
			Status:           model.StudioToolStateBeta,
		},

		// Video Tools (Queue 5: Initial Video Tool Activated)
		{
			Id:               "image-to-video",
			Slug:             "image-to-video",
			Name:             "Image to Video",
			DisplayName:      "แปลงภาพนิ่งเป็นวิดีโอ (Motion Magic)",
			Description:      "ขยับภาพถ่ายสินค้า ภาพวิว หรือภาพบุคคลให้มีชีวิตชีวาด้วยการเคลื่อนไหวระดับภาพยนตร์ สร้างคลิปวิดีโอความละเอียดสูง",
			Category:         "video",
			InputSchema:      `{"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string"},"motion_prompt":{"type":"string"},"duration":{"type":"integer","enum":[3,5],"default":5},"resolution":{"type":"string","enum":["720p","1080p"],"default":"720p"},"quality":{"type":"string","enum":["standard","high"],"default":"standard"},"audio":{"type":"boolean","default":false}}}`,
			OutputType:       "video/mp4",
			AllowedMIMETypes: "image/jpeg,image/png,image/webp",
			MaxUploadSize:    31457280,
			IsEnabled:        true,
			IsPublic:         true,
			CreditCost:       125,
			QuotaCost:        125000,
			RiskClass:        "high",
			DisplayOrder:     7,
			PrimaryProvider:  "fal",
			PrimaryModel:     "wan-video/wan-2.2",
			MarginPercent:    68.0,
			Status:           model.StudioToolStateActive,
		},

		// Disabled / Coming Soon Tools (Section 5)
		{
			Id:               "text-to-video",
			Slug:             "text-to-video",
			Name:             "Text to Video",
			DisplayName:      "สร้างวิดีโอจากข้อความ (เร็วๆ นี้)",
			Description:      "สร้างคลิปวิดีโอระดับภาพยนตร์จากคำบรรยายข้อความ",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       125,
			QuotaCost:        125000,
			DisplayOrder:     8,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "lip-sync",
			Slug:             "lip-sync",
			Name:             "Lip Sync Video",
			DisplayName:      "ลิปซิงก์เสียงและขยับปาก (เร็วๆ นี้)",
			Description:      "ซิงก์เสียงพูดภาษาไทยและภาษาอังกฤษเข้ากับริมฝีปากของวิดีโอ",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       75,
			QuotaCost:        75000,
			DisplayOrder:     9,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "face-swap",
			Slug:             "face-swap",
			Name:             "Face Swap Studio",
			DisplayName:      "สลับใบหน้าระดับโปร (เร็วๆ นี้)",
			Description:      "เปลี่ยนหน้าบุคคลในภาพด้วยความละเอียดระดับสตูดิโอ (ต้องการการยืนยันสิทธิ์)",
			Category:         "image",
			OutputType:       "image/png",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       40,
			QuotaCost:        40000,
			DisplayOrder:     10,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "talking-avatar",
			Slug:             "talking-avatar",
			Name:             "Talking Avatar",
			DisplayName:      "อวตารผู้ประกาศข่าว (เร็วๆ นี้)",
			Description:      "สร้างผู้ประกาศข่าวเสมือนจริงพูดรายงานจากสคริปต์",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       100,
			QuotaCost:        100000,
			DisplayOrder:     11,
			Status:           model.StudioToolStateComingSoon,
		},
		{
			Id:               "video-upscale",
			Slug:             "video-upscale",
			Name:             "Video Upscale (HD)",
			DisplayName:      "เพิ่มความคมชัดวิดีโอ (เร็วๆ นี้)",
			Description:      "ขยายวิดีโอความละเอียดต่ำขึ้นเป็น Full HD และ 4K",
			Category:         "video",
			OutputType:       "video/mp4",
			IsEnabled:        false,
			IsPublic:         false,
			CreditCost:       100,
			QuotaCost:        100000,
			DisplayOrder:     12,
			Status:           model.StudioToolStateComingSoon,
		},
	}

	for _, t := range tools {
		t.CreatedAt = now
		t.UpdatedAt = now
		var existing model.StudioToolDefinition
		if err := db.Where("id = ?", t.Id).First(&existing).Error; err != nil {
			_ = db.Select("*").Create(&t)
		} else {
			_ = db.Model(&existing).Select("*").Updates(&t)
		}
	}

	// 2. Useful Presets & Templates (Queue 4: Product Studio E-Commerce)
	templates := []model.StudioToolTemplate{
		// === 5 Marketplace Presets ===
		{
			Id:                "tpl-prod-shopee-1-1",
			ToolId:            "product-photo",
			Slug:              "shopee-1-1",
			Name:              "Shopee 1:1",
			DisplayName:       "Shopee Square (1:1)",
			Description:       "สัดส่วน 1:1 จัตุรัสมาตรฐานสำหรับรูปสินค้าหลัก Shopee จัดวางกึ่งกลางเด่นชัด พร้อมสำหรับการใส่กรอบโปรโมชัน",
			Category:          "marketplace",
			PresetPrompt:      "Clean commercial product photography on bright vibrant background, centered focal composition, Shopee product hero listing ready, crisp details, soft commercial lighting",
			PresetAspectRatio: "1:1",
			PresetParams:      `{"marketplace":"shopee","aspect_ratio":"1:1"}`,
			DisplayOrder:      1,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-lazada-1-1",
			ToolId:            "product-photo",
			Slug:              "lazada-1-1",
			Name:              "Lazada 1:1",
			DisplayName:       "Lazada Square (1:1)",
			Description:       "สัดส่วน 1:1 จัตุรัสระดับโปรสำหรับร้านค้า Lazada ภาพคมชัด ดึงดูดสายตาบนหน้า Search Feed",
			Category:          "marketplace",
			PresetPrompt:      "High-contrast clean advertising product shot, modern marketplace studio backdrop, balanced composition for Lazada search feed, sharp textures",
			PresetAspectRatio: "1:1",
			PresetParams:      `{"marketplace":"lazada","aspect_ratio":"1:1"}`,
			DisplayOrder:      2,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-instagram-4-5",
			ToolId:            "product-photo",
			Slug:              "instagram-4-5",
			Name:              "Instagram 4:5",
			DisplayName:       "Instagram Feed (4:5)",
			Description:       "สัดส่วน 4:5 แนวตั้งที่กินพื้นที่หน้าจอมือถือมากที่สุด เพิ่ม Engagement ให้โพสต์ร้านค้าบน Instagram",
			Category:          "marketplace",
			PresetPrompt:      "Aesthetic lifestyle product photo, 4:5 vertical framing for Instagram feed, editorial color grading, natural atmospheric lighting, high engagement look",
			PresetAspectRatio: "4:5",
			PresetParams:      `{"marketplace":"instagram","aspect_ratio":"4:5"}`,
			DisplayOrder:      3,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-story-9-16",
			ToolId:            "product-photo",
			Slug:              "story-9-16",
			Name:              "Story 9:16",
			DisplayName:       "Instagram / FB Story (9:16)",
			Description:       "สัดส่วน 9:16 เต็มจอมือถือ สำหรับ IG Story และ Facebook Story มีพื้นที่ด้านบน-ล่างสำหรับใส่สติกเกอร์และราคา",
			Category:          "marketplace",
			PresetPrompt:      "Vertical 9:16 mobile full-screen layout, lifestyle product presentation with clean negative space at top and bottom for text overlays and stickers",
			PresetAspectRatio: "9:16",
			PresetParams:      `{"marketplace":"story","aspect_ratio":"9:16"}`,
			DisplayOrder:      4,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-tiktok-9-16",
			ToolId:            "product-photo",
			Slug:              "tiktok-9-16",
			Name:              "TikTok Shop 9:16",
			DisplayName:       "TikTok Shop (9:16)",
			Description:       "สัดส่วน 9:16 สำหรับหน้าปกสินค้า TikTok Shop และวิดีโอปักตะกร้า ดึงดูดสายตาลูกค้าภายใน 1 วินาที",
			Category:          "marketplace",
			PresetPrompt:      "Vibrant high-energy vertical 9:16 framing, dynamic lighting, ultra crisp product highlight for TikTok Shop video showcase and live stream cover",
			PresetAspectRatio: "9:16",
			PresetParams:      `{"marketplace":"tiktok","aspect_ratio":"9:16"}`,
			DisplayOrder:      5,
			IsActive:          true,
		},

		// === 8 Visual Templates ===
		{
			Id:                "tpl-prod-white-studio",
			ToolId:            "product-photo",
			Slug:              "white-studio",
			Name:              "White Studio",
			DisplayName:       "สตูดิโอขาวไร้รอยต่อ (White Studio)",
			Description:       "ฉากหลังสีขาวสะอาดตาพร้อมเงาสะท้อนระดับสตูดิโอ ถูกต้องตามเกณฑ์รูปภาพหลักของทุกแพลตฟอร์ม",
			Category:          "visual_style",
			PresetPrompt:      "Clean seamless white studio background, commercial advertising lighting, soft ambient reflection, high-end product showcase, 8k resolution",
			PresetAspectRatio: "1:1",
			DisplayOrder:      11,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-luxury-black",
			ToolId:            "product-photo",
			Slug:              "luxury-black",
			Name:              "Luxury Black",
			DisplayName:       "หรูหราพรีเมียมสีดำ (Luxury Black)",
			Description:       "ฉากหลังหินสีดำดาร์กโทน แสงไฟ Rim Light ขับเน้นรูปทรง สำหรับสินค้าไฮเอนด์ นาฬิกา และน้ำหอม",
			Category:          "visual_style",
			PresetPrompt:      "Dark luxury minimalist stone background, dramatic moody rim light, premium cosmetic advertising, high contrast, elegant aesthetic",
			PresetAspectRatio: "1:1",
			DisplayOrder:      12,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-minimal-beige",
			ToolId:            "product-photo",
			Slug:              "minimal-beige",
			Name:              "Minimal Beige",
			DisplayName:       "มินิมอลเบจเอิร์ธโทน (Minimal Beige)",
			Description:       "โทนสีเบจและเนื้อไม้ธรรมชาติ สไตล์อบอุ่นสไตล์เกาหลี/มูจิ เหมาะกับสินค้าสกินแคร์และไลฟ์สไตล์",
			Category:          "visual_style",
			PresetPrompt:      "Warm beige linen background, wooden pedestal, soft natural morning sunlight casting organic leaf shadows, aesthetic lifestyle product shot",
			PresetAspectRatio: "4:5",
			DisplayOrder:      13,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-kitchen",
			ToolId:            "product-photo",
			Slug:              "kitchen-counter",
			Name:              "Kitchen",
			DisplayName:       "เคาน์เตอร์ครัวโมเดิร์น (Kitchen)",
			Description:       "ฉากครัวหินอ่อนโมเดิร์น สำหรับสินค้าเครื่องใช้ในครัว บรรจุภัณฑ์อาหาร และเครื่องดื่ม",
			Category:          "visual_style",
			PresetPrompt:      "Modern bright marble kitchen countertop, blurry warm kitchen background, daylight, lifestyle culinary photography",
			PresetAspectRatio: "1:1",
			DisplayOrder:      14,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-food",
			ToolId:            "product-photo",
			Slug:              "food-dining",
			Name:              "Food",
			DisplayName:       "โต๊ะอาหารและคาเฟ่ (Food & Dining)",
			Description:       "ฉากโต๊ะไม้บรรยากาศอบอุ่น แสงไฟธรรมชาติ เหมาะกับสินค้าอาหาร ขนม เบเกอรี่ และเครื่องดื่ม",
			Category:          "visual_style",
			PresetPrompt:      "Rustic wooden dining table, warm cafe ambiance, appetizing soft daylight, gourmet culinary background bokeh, commercial food presentation",
			PresetAspectRatio: "1:1",
			DisplayOrder:      15,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-cosmetics",
			ToolId:            "product-photo",
			Slug:              "cosmetics-podium",
			Name:              "Cosmetics",
			DisplayName:       "แท่นวางเครื่องสำอาง (Cosmetics Podium)",
			Description:       "แท่นอะคริลิกสีพาสเทลและละอองน้ำ แสงเงาละมุนตา เหมาะสำหรับเครื่องสำอาง เซรั่ม และสกินแคร์",
			Category:          "visual_style",
			PresetPrompt:      "Minimalist pastel acrylic pedestal, soft gradient backdrop, subtle water droplet reflections, clean beauty commercial lighting, delicate aesthetic",
			PresetAspectRatio: "4:5",
			DisplayOrder:      16,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-fashion",
			ToolId:            "product-photo",
			Slug:              "fashion-runway",
			Name:              "Fashion",
			DisplayName:       "แฟชั่นสตูดิโอ (Fashion & Apparel)",
			Description:       "ฉากคอนกรีตโมเดิร์นและแสงเงาสไตล์นิตยสารแฟชั่น เหมาะสำหรับเสื้อผ้า รองเท้า และกระเป๋า",
			Category:          "visual_style",
			PresetPrompt:      "Contemporary high-fashion concrete boutique backdrop, architectural soft shadows, sleek gallery aesthetic, Vogue style editorial product lighting",
			PresetAspectRatio: "4:5",
			DisplayOrder:      17,
			IsActive:          true,
		},
		{
			Id:                "tpl-prod-outdoor",
			ToolId:            "product-photo",
			Slug:              "outdoor-nature",
			Name:              "Outdoor",
			DisplayName:       "ธรรมชาติกลางแจ้ง (Outdoor Nature)",
			Description:       "ฉากหินแม่น้ำ ทุ่งหญ้า และแสงแดดอบอุ่น เหมาะกับสินค้าออร์แกนิกและกิจกรรมกลางแจ้ง",
			Category:          "visual_style",
			PresetPrompt:      "Natural outdoor setting on a smooth wet pebble stone, lush green foliage background bokeh, golden hour sunlight, organic aesthetic",
			PresetAspectRatio: "4:5",
			DisplayOrder:      18,
			IsActive:          true,
		},

		// Image Generation Templates
		{
			Id:                "tpl-img-pro-portrait",
			ToolId:            "image-generate",
			Slug:              "professional-portrait",
			Name:              "Professional Portrait",
			DisplayName:       "ภาพถ่ายบุคคลระดับโปร (Pro Headshot)",
			Description:       "ภาพถ่ายโปรไฟล์มืออาชีพสำหรับ LinkedIn และ Resume แสงแฟลชสตูดิโอคมชัด",
			Category:          "portrait",
			PresetPrompt:      "Corporate executive portrait, sharp focus on eyes, 85mm f/1.4 lens photography, studio softbox illumination, high detail facial skin texture",
			PresetAspectRatio: "4:5",
			DisplayOrder:      10,
			IsActive:          true,
		},
		{
			Id:                "tpl-img-cinematic",
			ToolId:            "image-generate",
			Slug:              "cinematic-film",
			Name:              "Cinematic Film",
			DisplayName:       "ภาพยนตร์ฟิล์ม (Cinematic 35mm)",
			Description:       "โทนภาพยนตร์ฟิล์ม 35mm แสงไฟ Dramatic อารมณ์ภาพทรงพลัง",
			Category:          "creative",
			PresetPrompt:      "Cinematic 35mm film still, anamorphic lens flare, moody color grading, volumetric smoke and haze, cinematic lighting, masterpiece",
			PresetAspectRatio: "16:9",
			DisplayOrder:      11,
			IsActive:          true,
		},
		{
			Id:                "tpl-img-anime",
			ToolId:            "image-generate",
			Slug:              "modern-anime",
			Name:              "Modern Anime",
			DisplayName:       "อนิเมะญี่ปุ่นร่วมสมัย (Makoto Shinkai Style)",
			Description:       "สไตล์อนิเมะญี่ปุ่นสีสันสดใส ท้องฟ้าและแสงแดดสไตล์ภาพยนตร์แอนิเมชัน",
			Category:          "creative",
			PresetPrompt:      "Vibrant modern anime visual key, Makoto Shinkai aesthetic, detailed cloud formations, emotional lighting, expressive character lineart",
			PresetAspectRatio: "16:9",
			DisplayOrder:      12,
			IsActive:          true,
		},

		// Image to Video Templates
		{
			Id:                "tpl-vid-product-ad-5s",
			ToolId:            "image-to-video",
			Slug:              "product-ad-5s",
			Name:              "Product Ad 5s",
			DisplayName:       "โฆษณาสินค้า 5 วินาที (Commercial Motion)",
			Description:       "การเคลื่อนกล้องแบบ Smooth Glide เน้นความเงางามของสินค้า สำหรับยิงแอด",
			Category:          "motion",
			PresetPrompt:      "Smooth camera pan around product, gentle light reflections, slow motion commercial videography",
			PresetAspectRatio: "1:1",
			DisplayOrder:      20,
			IsActive:          true,
		},
		{
			Id:                "tpl-vid-orbit-motion",
			ToolId:            "image-to-video",
			Slug:              "orbit-motion",
			Name:              "Orbit Motion",
			DisplayName:       "กล้องหมุนรอบวัตถุ (Orbit 360)",
			Description:       "กล้องหมุนโค้ง 45 องศา สร้างมิติและความพรีเมียมให้วัตถุ",
			Category:          "motion",
			PresetPrompt:      "Slow rotational orbit camera motion, steady gimbal movement, 3D depth parallax",
			PresetAspectRatio: "16:9",
			DisplayOrder:      21,
			IsActive:          true,
		},
		{
			Id:                "tpl-vid-zoom-in",
			ToolId:            "image-to-video",
			Slug:              "cinematic-zoom-in",
			Name:              "Cinematic Zoom In",
			DisplayName:       "ดอลลี่ซูมเข้า (Cinematic Push In)",
			Description:       "กล้องค่อยๆ เคลื่อนที่เข้าหาจุดกึ่งกลางอย่างนุ่มนวล ดึงดูดสายตา",
			Category:          "motion",
			PresetPrompt:      "Smooth slow dolly push-in towards focal subject, cinematic motion blur, 24fps film feel",
			PresetAspectRatio: "4:5",
			DisplayOrder:      22,
			IsActive:          true,
		},
		{
			Id:                "tpl-vid-vertical-reel",
			ToolId:            "image-to-video",
			Slug:              "vertical-reel-9-16",
			Name:              "Vertical Reel Motion (9:16)",
			DisplayName:       "คลิปสั้นแนวตั้ง TikTok/Reels (9:16)",
			Description:       "การเคลื่อนไหวน่าติดตาม สัดส่วน 9:16 สำหรับคลิปสั้นบนโซเชียลมีเดีย",
			Category:          "motion",
			PresetPrompt:      "Dynamic vertical video motion for TikTok and Instagram Reels, smooth transitions and lifelike movement",
			PresetAspectRatio: "9:16",
			DisplayOrder:      23,
			IsActive:          true,
		},
	}

	for _, tpl := range templates {
		tpl.CreatedAt = now
		tpl.UpdatedAt = now
		_ = db.Where("id = ?", tpl.Id).Assign(tpl).FirstOrCreate(&tpl)
	}

	// 3. Generic Media Relay Provider Configs (Queue 2F, Sections 3, 32, 35)
	providerConfigs := []model.StudioProviderConfig{
		{
			Id:           "wavespeed",
			Name:         "WaveSpeed AI",
			BaseURL:      "https://api.wavespeed.ai/api/v3",
			SecretEnv:    "WAVESPEED_API_KEY",
			AuthType:     "BEARER",
			Protocol:     model.ProtocolWaveSpeedV3,
			Enabled:      true,
			Priority:     1,
			HealthStatus: model.ProviderHealthActive,
		},
		{
			Id:           "kie",
			Name:         "KIE.ai",
			BaseURL:      "https://api.kie.ai",
			SecretEnv:    "KIE_API_KEY",
			AuthType:     "BEARER",
			Protocol:     model.ProtocolKieJobsV1,
			Enabled:      true,
			Priority:     2,
			HealthStatus: model.ProviderHealthActive,
		},
		{
			Id:           "fal",
			Name:         "Fal.ai",
			BaseURL:      "https://queue.fal.run",
			SecretEnv:    "FAL_KEY",
			AuthType:     "KEY_HEADER",
			Protocol:     model.ProtocolFalQueue,
			Enabled:      true,
			Priority:     3,
			HealthStatus: model.ProviderHealthBillingBlocked, // Fal is BILLING_BLOCKED per Section 35
		},
		{
			Id:           "replicate",
			Name:         "Replicate",
			BaseURL:      "https://api.replicate.com/v1",
			SecretEnv:    "REPLICATE_API_TOKEN",
			AuthType:     "BEARER",
			Protocol:     model.ProtocolReplicatePredictions,
			Enabled:      true,
			Priority:     4,
			HealthStatus: model.ProviderHealthActive,
		},
		{
			Id:           "mock",
			Name:         "Deterministic Mock",
			BaseURL:      "http://localhost",
			SecretEnv:    "MOCK_KEY",
			AuthType:     "CUSTOM",
			Protocol:     model.ProtocolMock,
			Enabled:      true,
			Priority:     10,
			HealthStatus: model.ProviderHealthActive,
		},
	}

	for _, cfg := range providerConfigs {
		cfg.CreatedAt = now
		cfg.UpdatedAt = now
		_ = db.Where("id = ?", cfg.Id).Assign(cfg).FirstOrCreate(&cfg)
	}

	// 4. Generic Media Model Routes (Queue 2F & 2G Canonical Routing)
	modelRoutes := []model.StudioModelRoute{
		// --- background-remove routes ---
		{
			Id:               "ws-birefnet",
			LogicalTool:      "background-remove",
			ProviderId:       "wavespeed",
			Protocol:         model.ProtocolWaveSpeedV3,
			ProviderModelId:  "wavespeed-ai/birefnet",
			QualityTier:      "FAST",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "DYNAMIC_API",
			BaseCostUSD:      0.004,
			EffectiveCostUSD: 0.004,
			PriceSource:      model.PriceSourceRemoteDynamic,
			PriceSourceRef:   "POST /api/v3/model/price",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         1,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"image_url":"image_url"}`,
		},
		{
			Id:               "kie-birefnet",
			LogicalTool:      "background-remove",
			ProviderId:       "kie",
			Protocol:         model.ProtocolKieJobsV1,
			ProviderModelId:  "rembg",
			QualityTier:      "FAST",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.005,
			EffectiveCostUSD: 0.005,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://docs.kie.ai/market/rembg",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         2,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"image_url":"image_url"}`,
		},
		{
			Id:               "fal-birefnet",
			LogicalTool:      "background-remove",
			ProviderId:       "fal",
			Protocol:         model.ProtocolFalQueue,
			ProviderModelId:  "fal-ai/birefnet",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusBillingBlocked,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.005,
			EffectiveCostUSD: 0.005,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://fal.ai/models/fal-ai/birefnet",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         3,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"image_url":"image_url"}`,
		},

		// --- image-upscale routes ---
		{
			Id:               "ws-upscaler",
			LogicalTool:      "image-upscale",
			ProviderId:       "wavespeed",
			Protocol:         model.ProtocolWaveSpeedV3,
			ProviderModelId:  "wavespeed-ai/image-upscaler",
			QualityTier:      "FAST",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "DYNAMIC_API",
			BaseCostUSD:      0.010,
			EffectiveCostUSD: 0.010,
			PriceSource:      model.PriceSourceRemoteDynamic,
			PriceSourceRef:   "POST /api/v3/model/price",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         1,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"image_url":"image_url"}`,
		},
		{
			Id:               "kie-upscale",
			LogicalTool:      "image-upscale",
			ProviderId:       "kie",
			Protocol:         model.ProtocolKieJobsV1,
			ProviderModelId:  "upscale-v1",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.012,
			EffectiveCostUSD: 0.012,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://docs.kie.ai/market/upscale",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         2,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"image_url":"image_url"}`,
		},
		{
			Id:               "fal-clarity",
			LogicalTool:      "image-upscale",
			ProviderId:       "fal",
			Protocol:         model.ProtocolFalQueue,
			ProviderModelId:  "fal-ai/clarity-upscaler",
			QualityTier:      "PREMIUM",
			Status:           model.RouteStatusBillingBlocked,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.015,
			EffectiveCostUSD: 0.015,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://fal.ai/models/fal-ai/clarity-upscaler",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         3,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"image_url":"image_url"}`,
		},

		// --- image-generate routes ---
		{
			Id:               "ws-flux-schnell",
			LogicalTool:      "image-generate",
			ProviderId:       "wavespeed",
			Protocol:         model.ProtocolWaveSpeedV3,
			ProviderModelId:  "wavespeed-ai/flux-schnell",
			QualityTier:      "FAST",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "DYNAMIC_API",
			BaseCostUSD:      0.0025,
			EffectiveCostUSD: 0.0025,
			PriceSource:      model.PriceSourceRemoteDynamic,
			PriceSourceRef:   "POST /api/v3/model/price",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         1,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","aspect_ratio":"aspect_ratio"}`,
		},
		{
			Id:               "kie-flux-schnell",
			LogicalTool:      "image-generate",
			ProviderId:       "kie",
			Protocol:         model.ProtocolKieJobsV1,
			ProviderModelId:  "flux-schnell",
			QualityTier:      "FAST",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.003,
			EffectiveCostUSD: 0.003,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://docs.kie.ai/market/flux-schnell",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         2,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","aspect_ratio":"aspect_ratio"}`,
		},
		{
			Id:               "ws-flux-dev",
			LogicalTool:      "image-generate",
			ProviderId:       "wavespeed",
			Protocol:         model.ProtocolWaveSpeedV3,
			ProviderModelId:  "wavespeed-ai/flux-dev",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "DYNAMIC_API",
			BaseCostUSD:      0.018,
			EffectiveCostUSD: 0.018,
			PriceSource:      model.PriceSourceRemoteDynamic,
			PriceSourceRef:   "POST /api/v3/model/price",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         1,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","aspect_ratio":"aspect_ratio"}`,
		},
		{
			Id:               "kie-flux-dev",
			LogicalTool:      "image-generate",
			ProviderId:       "kie",
			Protocol:         model.ProtocolKieJobsV1,
			ProviderModelId:  "flux-dev",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.020,
			EffectiveCostUSD: 0.020,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://docs.kie.ai/market/flux-dev",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         2,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","aspect_ratio":"aspect_ratio"}`,
		},
		{
			Id:               "fal-flux-dev",
			LogicalTool:      "image-generate",
			ProviderId:       "fal",
			Protocol:         model.ProtocolFalQueue,
			ProviderModelId:  "fal-ai/flux/dev",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusBillingBlocked,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.025,
			EffectiveCostUSD: 0.025,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://fal.ai/models/fal-ai/flux/dev",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         3,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","aspect_ratio":"aspect_ratio"}`,
		},

		// --- product-photo routes ---
		{
			Id:               "ws-product-flux",
			LogicalTool:      "product-photo",
			ProviderId:       "wavespeed",
			Protocol:         model.ProtocolWaveSpeedV3,
			ProviderModelId:  "wavespeed-ai/flux-dev",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "DYNAMIC_API",
			BaseCostUSD:      0.018,
			EffectiveCostUSD: 0.018,
			PriceSource:      model.PriceSourceRemoteDynamic,
			PriceSourceRef:   "POST /api/v3/model/price",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         1,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","image_url":"image_url"}`,
		},
		{
			Id:               "kie-product-flux",
			LogicalTool:      "product-photo",
			ProviderId:       "kie",
			Protocol:         model.ProtocolKieJobsV1,
			ProviderModelId:  "flux-dev",
			QualityTier:      "QUALITY",
			Status:           model.RouteStatusCredentialRequired,
			Enabled:          true,
			PricingStrategy:  "FIXED_COGS",
			BaseCostUSD:      0.020,
			EffectiveCostUSD: 0.020,
			PriceSource:      model.PriceSourceManualVerified,
			PriceSourceRef:   "https://docs.kie.ai/market/flux-dev",
			PriceVerifiedAt:  now,
			PricingVersion:   "v2_canonical",
			Priority:         2,
			MinMargin:        60.0,
			SuccessRate:      100.0,
			InputMapping:     `{"prompt":"prompt","image_url":"image_url"}`,
		},
	}

	for _, route := range modelRoutes {
		route.CreatedAt = now
		route.UpdatedAt = now
		_ = db.Where("id = ?", route.Id).Assign(route).FirstOrCreate(&route)
	}

	return nil
}
